services:
    brp_notification_sender:
        class: Brp\NotificationSenderBundle\Sender\BrpNotificationSender
        arguments: ["@brp_notification_sender.entity_manager", "@logger"]

    brp_notification_sender.entity_manager:
        class: Doctrine\Common\Persistence\ObjectManager
        factory_service: doctrine
        factory_method: getManager
        arguments: [ '%brp_notification_sender.entity_manager%' ]