services:
    brp_notification_sender:
        class: Brp\NotificationSenderBundle\Sender\BrpNotificationSender
        arguments: ["@brp_notification_sender.entity_manager", "@logger"]

    brp_notification_sender.entity_manager:
        class: Doctrine\ORM\EntityManager
        factory: 'doctrine:getManager'
        arguments: [ '%brp_notification_sender.entity_manager%' ]