<?php

namespace Brp\NotificationSenderBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationTemplateRepository extends EntityRepository
{
    public function getNotificationTemplatesByCode($code)
    {
        return $this->findBy(
            ['notificationCode' => $code, 'enabled' => true]
        );
    }
}