<?php

namespace Brp\NotificationSenderBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProviderParamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProviderParameterRepository extends EntityRepository
{
    public function getCodeValueParamsArray($provider)
    {
        $result = array();

        $qb = $this->createQueryBuilder('p')
            ->select('p.code, p.value')
            ->where('p.provider = :provider')
            ->setParameter('provider', $provider)
            ;

        $queryResults = $qb->getQuery()->getArrayResult();

        foreach($queryResults as $qr) {
            $result[$qr['code']] = $qr['value'];
        }

        return $result;
    }
}
